### ISSUE TITLE
项目1 | 猜数字的问题

### ISSUE THREAD

**Issue by imlinhanchao** [zhengzongsheng/szisa_traning#1]
题目不是0~1000吗？
https://github.com/zhengzongsheng/szisa_traning/blob/a6e3aa52aaf62e2a65115c32b8ed54df20dbbc3b/03-21-%E7%8C%9C%E6%95%B0%E5%AD%97.java#L8

如果猜了100次都没中，程序就会莫名退出？
https://github.com/zhengzongsheng/szisa_traning/blob/a6e3aa52aaf62e2a65115c32b8ed54df20dbbc3b/03-21-%E7%8C%9C%E6%95%B0%E5%AD%97.java#L12

**Comment by zhengzongsheng** [comment]
问题已解决

**Comment by imlinhanchao** [comment]
更好的写法是
```java
while(true) {
```
https://github.com/zhengzongsheng/szisa_traning/blob/6ccc7c262e464d019d0337583e828316d022425c/03-21-%E7%8C%9C%E6%95%B0%E5%AD%97.java#L12

**Comment by imlinhanchao** [comment]
确认问题已修复。
