### ISSUE TITLE
项目1 | 网站设计的问题

### ISSUE THREAD

**Issue by imlinhanchao** [zhengzongsheng/szisa_traning#2]
1. 如果高度太小，就会出现这种问题。
![image](https://user-images.githubusercontent.com/1502581/37563337-9c36be64-2ab9-11e8-98ad-c8ef9e585f3f.png)
https://github.com/zhengzongsheng/szisa_traning/blob/a6e3aa52aaf62e2a65115c32b8ed54df20dbbc3b/03-21-%E7%BD%91%E7%AB%99%E8%AE%BE%E8%AE%A1/css/main.css#L64

2. 最好有一个最小宽度，这样在宽屏模式下不会看起来整个是拉长的。
![image](https://user-images.githubusercontent.com/1502581/37563359-f64f8822-2ab9-11e8-94f7-b01b78b41ddc.png)

**Comment by zhengzongsheng** [comment]
问题已解决

**Comment by imlinhanchao** [comment]
![image](https://user-images.githubusercontent.com/1502581/37577449-2e5342fa-2b6d-11e8-9e21-5190736b9ce4.png)

不应该使用`margin-top`来实现往下顶。这样在本身高度足够的情况下，可能会出现滚动条。

https://github.com/zhengzongsheng/szisa_traning/blob/6ccc7c262e464d019d0337583e828316d022425c/03-21-%E7%BD%91%E7%AB%99%E8%AE%BE%E8%AE%A1/css/main.css#L64-L70

你其实已经想到用绝对定位，只是，你的网页高度没有撑满整个浏览器。

**Comment by zhengzongsheng** [comment]
问题已解决[03-21-网站设计](https://github.com/zhengzongsheng/szisa_traning/tree/master/03-21-%E7%BD%91%E7%AB%99%E8%AE%BE%E8%AE%A1) @imlinhanchao
