### ISSUE TITLE
项目2 | 网页设计第二期需求问题

### ISSUE THREAD

**Issue by imlinhanchao** [zhengzongsheng/szisa_traning#3]
1. 题目要求是在输入不正确时就提示，而非点击按钮时才提示。
2. 按钮禁用样式不明显，一般应当设置为变灰。可以通过**属性选择器**做到。

**Comment by zhengzongsheng** [comment]
问题已解决[03-29-表单验证](https://github.com/zhengzongsheng/szisa_traning/tree/master/03-29-%E8%A1%A8%E5%8D%95%E9%AA%8C%E8%AF%81) @imlinhanchao

**Comment by zhengzongsheng** [comment]
首先在用a之前有考虑过用h1/2/3/4/5/6、p等标签，但所呈现的效果都会在字体前后创建一些空白，影响美观；如果不能用a，b也可以考虑一下（粗体不好看），自定义也不是不可以
