### ISSUE TITLE
项目三 | Ajax请求项目问题

### ISSUE THREAD

**Issue by imlinhanchao** [zhengzongsheng/szisa_traning#4]
审题不严，提示错误。
https://github.com/zhengzongsheng/szisa_traning/blob/86dcb4b6ea76eb1fd035117c05ddaf7db5e94a69/04-11-Ajax%E8%AF%B7%E6%B1%82/js/main.js#L47-L53

**Comment by zhengzongsheng** [comment]
问题已解决 [Ajax请求项目问题](https://github.com/zhengzongsheng/szisa_traning/tree/master/04-11-Ajax%E8%AF%B7%E6%B1%82) @imlinhanchao
