### ISSUE TITLE
项目4 | 设置猜测数字范围问题

### ISSUE THREAD

**Issue by imlinhanchao** [zhengzongsheng/szisa_traning#5]
1. 没有保存猜测数字范围，下次开启依然从1000开始；
2. 没有在记录中保存猜测数字范围，这个需求应该是隐含的。

**Comment by zhengzongsheng** [comment]
问题已解决[04-18-可设置的猜数字范围](https://github.com/zhengzongsheng/szisa_traning/tree/master/04-18-%E5%8F%AF%E8%AE%BE%E7%BD%AE%E7%9A%84%E7%8C%9C%E6%95%B0%E5%AD%97%E8%8C%83%E5%9B%B4) @imlinhanchao

**Comment by zhengzongsheng** [comment]
问题已解决[04-18-可设置的猜数字范围](https://github.com/zhengzongsheng/szisa_traning/tree/master/04-18-%E5%8F%AF%E8%AE%BE%E7%BD%AE%E7%9A%84%E7%8C%9C%E6%95%B0%E5%AD%97%E8%8C%83%E5%9B%B4) @imlinhanchao
